[package]
name = "apollo-cli"
version = "0.0.2"
authors = ["Apollo <opensource@apollographql.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atlas = { path = "../atlas" }
structopt = "*"
serde = "1.0"
failure = "*"
graphql-parser = { path = "../graphql-parser" }
log = { version = "0.4", features = ["std"] }
dirs = "2.0"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"


[target.'cfg(windows)'.dependencies]
winreg = "0.7.0"