blank_issues_enabled: true
contact_links:
  - name: "📚 Questions: Stack Overflow tagged \"apollo\""
    url: https://stackoverflow.com/questions/tagged/apollo
    about: >-
      Many questions are already answered on Stack Overflow!
      We suggest starting here!
  - name: "💬 Questions: Apollo GraphQL Community"
    url: https://community.apollographql.com/
    about: >-
      If you're unable to find an answer on Stack Overflow, the Apollo GraphQL Community is the next best place.
