[package]
name = "harmonizer-bin"
version = "0.1.0"
authors = ["Apollo Developers <opensource@apollographql.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# workspace deps
harmonizer = { path = "../harmonizer" }
