name: Deploy CDN Proxy

on:
  push:
    branches:
      - master
    paths:
      - 'cdn/**/*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          USER: root
        steps:
          - uses: actions/checkout@v2

          - name: Publish
            uses: cloudflare/wrangler-action@1.1.0
            with:
              apiToken: ${{ secrets.CF_API_TOKEN }}
              workingDirectory: 'cdn'


          - name: Create Deployment
            id: deploy
            uses: abendigo/create-deployment@v1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}