name: Publish on Release

on:
  release:
    types: published

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Publish
        uses: Enrico2/Publish-Docker-Github-Action@master
        with:
          name: apollographql/federation/stargate
          username: ${{ github.actor }}
          # Must be a PAT to publish to GHCR
          # See: https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry
          password: ${{ secrets.PUBLISH_DEBUG_TSCHEER }}
          workdir: /github/workspace/stargate
          registry: ghcr.io
          tag_semver: true
          include_latest: true