name: Tests

on: [pull_request]

jobs:
  test:
    name: Test Rust Packages

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          [
            linux-stable,
            # linux-nightly,
            macos-stable,
            # macos-nightly,
            windows-stable,
            # windows-nightly,
          ]
        include:
          - build: linux-stable
            os: ubuntu-latest
            rust: stable
          - build: macos-stable
            os: macos-latest
            rust: stable
          - build: windows-stable
            os: windows-latest
            rust: stable
          # - build: linux-nightly
          #   os: ubuntu-latest
          #   rust: nightly
          # - build: macos-nightly
          #   os: macos-latest
          #   rust: nightly
          # - build: windows-nightly
          #   os: windows-latest
          #   rust: nightly

    steps:
      - uses: actions/checkout@v2

      - name: Cache Cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.build }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.build }}-${{ matrix.rust }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ matrix.build }}-${{ matrix.rust }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.build }}-${{ matrix.rust }}-cargo-index-

      - name: Cache Cargo build
        uses: actions/cache@v1
        with:
          path: target/debug
          key: ${{ matrix.build }}-${{ matrix.rust }}-debug-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.build }}-${{ matrix.rust }}-debug-target-

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}

      - name: Run Tests
#        if: matrix.build != 'linux-stable'
        run: cargo test
        env:
          RUST_LOG: warn,apollo-cli=info
          RUST_BACKTRACE: 1

# Restore this when we get coverage working well -- integration tests on binary packages don't report coverage correctly.
#      - name: Run cargo-tarpaulin
#        if: matrix.build == 'linux-stable'
#        uses: actions-rs/tarpaulin@v0.1
#        with:
#          version: '0.9.0'
#          timeout: 600 # 10 mins for test coverage
#          args: '--ignore-tests'
  
      - name: Upload to codecov.io
        if: matrix.build == 'linux-stable'
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  test_worker:
    name: Test CDN and installer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdn

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Cache Node.js modules
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

    - name: Install dependencies
      run: npm ci

    - run: npm test -- --coverage
      env:
        CI: true

    - name: Upload worker results to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        name: cdn

    - name: Use Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    
    - name: Install bashcov for installer coverage
      run: |
        gem install bashcov
        gem install codecov
    
    - name: Run coverage for installer
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      run: bashcov --skip-uncovered -- ./node_modules/.bin/bats ./test/*.bats
